add on-merge policy

diff --git a/{{cookiecutter.app_name}}/.github/workflows/build.yaml b/{{cookiecutter.app_name}}/.github/workflows/build.yaml
--- a/{{cookiecutter.app_name}}/.github/workflows/build.yaml
+++ b/{{cookiecutter.app_name}}/.github/workflows/build.yaml
@@ -6,6 +6,9 @@ on:
     branches:
       - master
 
+env:
+  COVERAGE_THRESHOLD: 0  # set unit test coverage threshold percentage. Reject PR if coverage is blow threshold.
+
 jobs:
   build-test:
     runs-on: ubuntu-latest
@@ -33,8 +36,43 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-go-
 
-      - name: Run Unit tests
+      - name: Run Unit tests & calculate coverage
+        id: unit-test
         run: |-
-          cp ./params/hello.toml.sample ./params/hello.toml
-          go test -race ./...
+          cp ./params/.env.sample ./params/.env
+          go test -race -covermode=atomic -coverprofile=coverage-reports.out ./...
+          echo "::set-output name=totalcoverage::$(go tool cover -func coverage-reports.out | grep total | awk '{print substr($3, 1, length($3)-1)}')"
+
+      - name: Print PR comment if unit test below threshold
+        if: steps.unit-test.outputs.totalcoverage < env.COVERAGE_THRESHOLD
+        uses: KeisukeYamashita/create-comment@v1
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          unique: true
+          check-only-first-line: true
+          comment: |
+            ##  <img src="https://golang.org/lib/godoc/images/go-logo-blue.svg" height="15" /> Unit Test Coverage
+            Current coverage: ${{ steps.unit-test.outputs.totalcoverage }}%
+            Threshold : ${{ env.COVERAGE_THRESHOLD }}%
+            Status : ❌ PR blocked! Your coverage is lower than threshold.
+            > _you can update the threshold on `.github/workflows/build.yaml`_
+
+      - name: Failing job if unit test below threshold
+        if: steps.unit-test.outputs.totalcoverage < env.COVERAGE_THRESHOLD
+        run: |-
+          echo "::error ::Total unit test coverage is below threshold"
+          exit 1
+
+      - name: Report existing coverage to PR comment if unit test pass threshold
+        uses: KeisukeYamashita/create-comment@v1
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          unique: true
+          check-only-first-line: true
+          comment: |
+            ##  <img src="https://golang.org/lib/godoc/images/go-logo-blue.svg" height="15" /> Unit Test Coverage
+            Current coverage: ${{ steps.unit-test.outputs.totalcoverage }}%
+            Threshold : ${{ env.COVERAGE_THRESHOLD }}%
+            Status : ✅ Passed. Keep improving your coverage.
+            > _you can update the threshold on `.github/workflows/build.yaml`_
 {%- endraw %}
